name: tilepredictor
channels:
  - defaults
dependencies:
  - python=2.7.15
  - numpy=1.14.3
  - six=1.12.0
  - pillow=5.2.0
  - scikit-image=0.14.0
  - keras=2.2.2
  - pip=19.3.1
  - pip:
    - spectral==0.19
